/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author vijaya
 */
public class SubjectListView extends javax.swing.JFrame {
    public static final Date d = new Date();

    /**
     * Creates new form SubjectListView
     */
    public SubjectListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Date thuDate = new Date();
        SpinnerDateModel tsdmf =
        new SpinnerDateModel(thuDate,null,null,Calendar.HOUR_OF_DAY);
        thuTimeFrom = new javax.swing.JSpinner(tsdmf);
        Date friDate = new Date();
        SpinnerDateModel frisdmf = new SpinnerDateModel(friDate,null,null,Calendar.HOUR_OF_DAY);
        friTimeFrom = new javax.swing.JSpinner(frisdmf);
        Date mdt = new Date();
        SpinnerDateModel msdt=new SpinnerDateModel(mdt, null, null, Calendar.HOUR_OF_DAY);
        monTimeTo = new javax.swing.JSpinner(msdt);
        Date satDate = new Date();
        SpinnerDateModel satsdmf = new SpinnerDateModel(satDate,null,null,Calendar.HOUR_OF_DAY);
        satTimeFrom = new javax.swing.JSpinner(satsdmf);
        Date selecteDate = new Date();
        SpinnerDateModel spinnerDateModel =
        new SpinnerDateModel(selecteDate,null,null,Calendar.HOUR_OF_DAY);
        sunTimeFrom1 = new javax.swing.JSpinner(spinnerDateModel);
        Date mdf = new Date();
        SpinnerDateModel msdf=new SpinnerDateModel(mdf, null, null, Calendar.HOUR_OF_DAY);
        monTimeFrom = new javax.swing.JSpinner(msdf);
        Date tueDate = new Date();
        SpinnerDateModel tuesdmf = new SpinnerDateModel(tueDate,null,null,Calendar.HOUR_OF_DAY);
        TueTimeFrom = new javax.swing.JSpinner(tuesdmf);
        Date WedDate = new Date();
        SpinnerDateModel Wedsdmf = new SpinnerDateModel(WedDate,null,null,Calendar.HOUR_OF_DAY);
        WedTimeFrom = new javax.swing.JSpinner(Wedsdmf);
        Date wd = new Date();
        SpinnerDateModel wsdt=new SpinnerDateModel(wd, null, null, Calendar.HOUR_OF_DAY);
        wedTimeTo = new javax.swing.JSpinner(wsdt);
        Date thdt = new Date();
        SpinnerDateModel thusdt=new SpinnerDateModel(thdt, null, null, Calendar.HOUR_OF_DAY);
        thuTimeTo = new javax.swing.JSpinner(thusdt);
        Date tdt = new Date();
        SpinnerDateModel tsdt=new SpinnerDateModel(tdt, null, null, Calendar.HOUR_OF_DAY);
        tueTimeTo = new javax.swing.JSpinner(tsdt);
        Date fhdt = new Date();
        SpinnerDateModel fhusdt=new SpinnerDateModel(fhdt, null, null, Calendar.HOUR_OF_DAY);
        friTimeTo = new javax.swing.JSpinner(fhusdt);
        Date sathdt = new Date();
        SpinnerDateModel sathusdt=new SpinnerDateModel(sathdt, null, null, Calendar.HOUR_OF_DAY);
        SaTimeTo = new javax.swing.JSpinner(sathusdt);
        Date d = new Date();
        SpinnerDateModel sdm=new SpinnerDateModel(d, null, null, Calendar.HOUR_OF_DAY);
        sunTimeTo = new javax.swing.JSpinner(sdm);
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Grade :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Subject :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("From");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("To");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        JSpinner.DateEditor tdef=new JSpinner.DateEditor(thuTimeFrom,"HH:mm a");
        thuTimeFrom.setEditor(tdef);
        jPanel1.add(thuTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, -1));

        JSpinner.DateEditor fridef=new JSpinner.DateEditor(friTimeFrom,"HH:mm a");
        friTimeFrom.setEditor(fridef);
        jPanel1.add(friTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 90, -1));

        JSpinner.DateEditor mjsdt= new JSpinner.DateEditor(monTimeTo,"HH:mm a");
        monTimeTo.setEditor(mjsdt);
        jPanel1.add(monTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 90, -1));

        JSpinner.DateEditor satdef=new JSpinner.DateEditor(satTimeFrom,"HH:mm a");
        satTimeFrom.setEditor(satdef);
        jPanel1.add(satTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 90, -1));

        JSpinner.DateEditor dateEditor=new JSpinner.DateEditor(sunTimeFrom1,"HH:mm a");
        sunTimeFrom1.setEditor(dateEditor);
        jPanel1.add(sunTimeFrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        JSpinner.DateEditor mjsde= new JSpinner.DateEditor(monTimeFrom,"HH:mm a");
        monTimeFrom.setEditor(mjsde);
        jPanel1.add(monTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, -1));
        JSpinner.DateEditor tuedef=new JSpinner.DateEditor(TueTimeFrom,"HH:mm a");
        TueTimeFrom.setEditor(tuedef);
        jPanel1.add(TueTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, -1));

        JSpinner.DateEditor Wedjsde= new JSpinner.DateEditor(WedTimeFrom,"HH:mm a");
        WedTimeFrom.setEditor(Wedjsde);
        jPanel1.add(WedTimeFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));

        JSpinner.DateEditor wjsdt= new JSpinner.DateEditor(wedTimeTo,"HH:mm a");
        wedTimeTo.setEditor(wjsdt);
        jPanel1.add(wedTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 90, -1));

        JSpinner.DateEditor thujsdt= new JSpinner.DateEditor(thuTimeTo,"HH:mm a");
        thuTimeTo.setEditor(thujsdt);
        jPanel1.add(thuTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 90, -1));

        JSpinner.DateEditor tjsdt= new JSpinner.DateEditor(tueTimeTo,"HH:mm a");
        tueTimeTo.setEditor(tjsdt);
        jPanel1.add(tueTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 90, -1));

        JSpinner.DateEditor fjsdt= new JSpinner.DateEditor(friTimeTo,"HH:mm a");
        friTimeTo.setEditor(fjsdt);
        jPanel1.add(friTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 90, -1));

        JSpinner.DateEditor satjsdt= new JSpinner.DateEditor(SaTimeTo,"HH:mm a");
        SaTimeTo.setEditor(satjsdt);
        jPanel1.add(SaTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 90, -1));

        JSpinner.DateEditor jsde= new JSpinner.DateEditor(sunTimeTo,"HH:mm a");
        sunTimeTo.setEditor(jsde);
        jPanel1.add(sunTimeTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 90, -1));

        jCheckBox1.setText("Sat");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jCheckBox2.setText("Fri");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jCheckBox3.setText("Thu");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jCheckBox4.setText("Wed");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jCheckBox5.setText("Tue");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jCheckBox6.setText("Mon");
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jCheckBox7.setText("Sun");
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Fee :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 90, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resoures/bg_lkup.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectListView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SaTimeTo;
    private javax.swing.JSpinner TueTimeFrom;
    private javax.swing.JSpinner WedTimeFrom;
    private javax.swing.JSpinner friTimeFrom;
    private javax.swing.JSpinner friTimeTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner monTimeFrom;
    private javax.swing.JSpinner monTimeTo;
    private javax.swing.JSpinner satTimeFrom;
    private javax.swing.JSpinner sunTimeFrom1;
    private javax.swing.JSpinner sunTimeTo;
    private javax.swing.JSpinner thuTimeFrom;
    private javax.swing.JSpinner thuTimeTo;
    private javax.swing.JSpinner tueTimeTo;
    private javax.swing.JSpinner wedTimeTo;
    // End of variables declaration//GEN-END:variables
}
